version: '2.1'

services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: healthcheck/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=oauth2_laravel
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
