version: '2'

services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=oauth2_laravel
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
